### PR TITLE
Fix miscellaneous errors during conversion 

### PR DESCRIPTION
**Pull request by LDVG**
I ran into two issues when converting my bank statement using this plugin, contributing with what I had to do to fix them:

- The `Text  / mottagare` field no longer contains spaces, because of this the plugin asserts and stops. To remedy this, the spaces are removed from the assert (change is assumed to be global for all SEB users). 
- The `saldo` field may already be parsed as a float (Python 3?), and the `atof` operation therefore fails; only do `atof` if the `saldo` variable is a string.

Thanks for this useful plugin!

### CODE REVIEW

**Comment by themalkolm** [comment]
Float parsing is locale sensitive. Different locales parse float differently, right? This is why we have locale configuration option.

**Comment by themalkolm** [comment]
I'd prefer to fix spaces keeping backward compatibility. Something like 

```
[...] = map(lambda _: _.replace(' ', ''), statement_header_row)
```

**Comment by LDVG** [comment]
> Float parsing is locale sensitive. Different locales parse float differently, right? This is why we have locale configuration option. Try to change it.

Setting locale to `sv_SE` raises an attribute error when I try to run without the modification, Python version is 3.5.2 (ofxstatement 1.0.0, openpyxl 2.5.3). Attaching last part of the traceback below

```
[...]
  File "/usr/lib/python3.5/locale.py", line 317, in atof
    return func(delocalize(string))
  File "/usr/lib/python3.5/locale.py", line 308, in delocalize
    string = string.replace(ts, '')
AttributeError: 'float' object has no attribute 'replace'
```

> I'd prefer to fix spaces keeping backward compatibility. Something like
> 
> ```[...] = map(lambda _: _.replace(' ', ''), statement_header_row)```

I completely agree, I will change my pull request with an appropriate solution. :+1:

**Comment by themalkolm** [comment]
Oh, my bad. You mean atof fails of it is already a float.

**Comment by LDVG** [comment]
Exactly. I have now rebased my changes after your feedback. :-)

**Comment by themalkolm** [comment]
I had same issue in another plugin https://github.com/themalkolm/ofxstatement-lfs/blob/master/ofxstatement/plugins/lfs.py#L89

**Comment by themalkolm** [comment]
I will do couple of cleanup commits to not bother you here.

**Comment by themalkolm** [comment]
Of course! openpyxl will do its own part of parsing. Then we have another problem that we are going to pass either float or integer down to ofx.

**Comment by themalkolm** [comment]
Scratch that. You actually thought about this and used Real instead of Numbers.

**Comment by themalkolm** [comment]
k, lets check for int as well. I think it should work now.

**Comment by LDVG** [comment]
> k, lets check for int as well. I think it should work now.

Looking good! One small mistake snuck its way into the code; in the map call you use `self.sanitize_header` but the function is defined as `canonicalize_header`. :-)

**Comment by themalkolm** [comment]
Fix it! Now it is your turn!

**Pull request merged**
